### ISSUE TITLE
Homepage Side menu 

### ISSUE THREAD

**Issue by jachambel** [trilbymedia/grav-skeleton-typhoon-rockets#1]
I am installing a website with the typhoon theme and I need to enable the side menu on the main page. how can I do this?
Thank's.

**Comment by w00fz** [comment]
Not sure if this is what you are asking but there’s an option that puts the children in the sidebar as opposed as the default dropdown behavior.

https://getgrav.org/premium/typhoon/docs#advanced-typhoon-options

> Also FYI, we have a dedicated repository for Grav Premium issues: https://github.com/getgrav/grav-premium-issues

**Comment by jachambel** [comment]
Thanks for the quick response. I will report an issue in that repository.
